# Generated by Django 4.1.5 on 2023-01-25 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_one', models.CharField(max_length=50)),
                ('question_two', models.CharField(max_length=50)),
                ('question_three', models.CharField(max_length=50)),
                ('question_four', models.CharField(max_length=50)),
                ('question_five', models.CharField(max_length=50)),
                ('question_six', models.CharField(max_length=50)),
                ('question_seven', models.CharField(max_length=50)),
                ('question_eight', models.CharField(max_length=50)),
                ('question_nine', models.CharField(max_length=50)),
                ('question_ten', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
